### ISSUE TITLE
Is Jetpack still needed for WP 4.4?

### ISSUE THREAD

**Issue by senlin** [carrot/roots-wordpress#10]
Now that the JSON REST API is added to Core (WordPress 4.4), is it still necessary to download Jetpack?

**Comment by kylemac** [comment]
@senlin we haven't tested this out on WP 4.4 yet, but unless the endpoints have changed - it should still work out-of-the-box. could you give it a run and let us know, perhaps?

**Comment by senlin** [comment]
I have [another problem](https://github.com/carrot/roots-wordpress/issues/11) which makes it impossible for me to confirm whether it works or not.

**Comment by senlin** [comment]
end points are in phase 2, scheduled to be released in WP 4.5, so probably for now Jetpack still works best
