### ISSUE TITLE
Segmentation fault: 11 on compiling

### ISSUE THREAD

**Issue by senlin** [carrot/roots-wordpress#11]
Getting a _Segmentation fault 11_ after attempting to run `roots watch` 
Already re-installed the lot to see if that would make a difference, but no joy.
Anyone has an idea? I'm on OSX 10.11 node version 4.1.2 and npm version 2.14.6

```
$ roots watch
compiling... [Error: [object Object]]

Segmentation fault: 11
```

**Comment by kylemac** [comment]
@senlin does this happen each time? we have seen this issue in some rare cases, but not for every compile.

**Comment by senlin** [comment]
Hi Kyle, unfortunately yes, on each and every compile. I have yet to be able to run a successful `roots watch` command.

Maybe it has to do with the fact that I cannot visit localhost:1111 (I have built an AMP stack with a Virtual Hosts file)?

I tried to run a `roots compile` command and got the following output:

```
compiling... { [Error: Uncaught, unspecified "error" event. ([object Object])]
  context: 
   { request: 
      { path: 'https://public-api.wordpress.com/rest/v1/sites/sandbox-online.com/wptips/posts',
        params: [Object],
        originator: [Object],
        headers: [Object],
        method: 'GET',
        canceled: false,
        cancel: [Function: cancel] },
     raw: { request: [Object], response: [Object] },
     status: { code: 404 },
     headers: 
      { Server: 'nginx',
        Date: 'Tue, 10 Nov 2015 17:41:38 GMT',
        'Content-Type': 'text/plain;charset=utf-8',
        'Transfer-Encoding': 'chunked',
        Connection: 'close',
        Vary: 'Accept-Encoding',
        'X-Prefork': '1',
        'X-Hacker': 'Oh, Awesome: Opossum',
        Expires: 'Wed, 11 Jan 1984 05:00:00 GMT',
        'Cache-Control': 'no-cache, must-revalidate, max-age=0',
        Pragma: 'no-cache',
        'Access-Control-Allow-Origin': '*',
        'X-Ac': '2.hkg _dfw' },
     entity: '' } }
```

The path above seems strange. Followed the screencast to the t, done nothing different.

**Comment by senlin** [comment]
3rd time lucky as they say, I finally managed to get it working :)
