### ISSUE TITLE
Advanced Custom Fields

### ISSUE THREAD

**Issue by fathert0rque** [carrot/roots-wordpress#7]
Do you have any insight as to how to pull in metadata from custom fields, more specifically, the [Advanced Custom Fields](http://www.advancedcustomfields.com/) plugin?

From what I have read it seems that you have to whitelist metadata keys to be pulled in from Jetpack's JSON API, but this could prove cumbersome for a site that has dozens or hundreds of custom fields.

I was thinking of taking a stab at a pull request, but was wondering if you had given it any thought before I began.

**Comment by kylemac** [comment]
@chrisbarless we, unfortunately, haven't tried pulling in custom fields yet. a google shows a sad un-initiated response to the same question: http://support.advancedcustomfields.com/forums/topic/jetpack-json-api/

**Comment by kylemac** [comment]
it appears that jetpack is OSS too - https://github.com/Automattic/jetpack - which bodes well with being able to get around this if it is a limitation. 

it obviously would require the installation of a forked plugin (and cut off support for wordpress.com users) but it could be worth it to some folks, if that is the direction it has to go

**Comment by fathert0rque** [comment]
Ah, that is very unfortunate. Custom field support is super important to most custom WP developers' workflow. I'm surprised they haven't given it more attention.

Oh well, you can't win 'em all.

**Comment by janwirth** [comment]
It is possible! You have to make an addition to the wordpress backend though.
http://stackoverflow.com/questions/10132685/json-api-to-show-advanced-custom-fields-wordpress

**Comment by roti-dev** [comment]
@FranzSkuffka So I've managed to get Wordpress to display my ACF data via JSON API , but this Roots extension was built around JetPack's wordpress.org solution.

Is it possible to get my roots setup / this extension to the JSON API setup instead?

**Comment by janwirth** [comment]
Unfortunately I do not know any more / cannot help you.

**Comment by jescalan** [comment]
Hey @chrisbarless! I am the author of roots, just here to mention that at this point roots isn't actively maintained or developed, and future efforts are going into [spike](https://github.com/static-dev/spike). That being said, if you are interested in working on plugins or functionality to make this happen, you are very welcome to contribute! I'm happy to help as I can along the way, and if you are able to make it work I will merge/ship your modifications.

Good luck!
