### ISSUE TITLE
Watcher breaks on save.

### ISSUE THREAD

**Issue by janwirth** [carrot/roots-wordpress#9]
When saving my post template file, I get this error every time and have to restart the watcher:
<code>ENOENT, no such file or directory '/home/jan/wordpress-roots/assets/img/layout.jade'</code>

**Comment by jescalan** [comment]
This is not a roots-wordpress error, it's an error with jade layouts. I'd need to know more to diagnose it 100% but it looks like you have a jade file in your images folder to me. Closing but welcome to continue discussion!
